# Generated by Django 6.1 on 2026-08-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('taxonamy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(blank=True, max_length=500, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='taxonamy.taxonomyattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_attributes', to='taxonamy.taxonomyvalue')),
            ],
            options={
                'db_table': 'product_attributes',
                'indexes': [models.Index(fields=['product'], name='product_att_product_a8d59b_idx'), models.Index(fields=['attribute'], name='product_att_attribu_5046cc_idx'), models.Index(fields=['value'], name='product_att_value_i_13b095_idx')],
            },
        ),
    ]
