# Generated by Django 6.1 on 2026-08-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('taxonamy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('rank', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('RULE', 'Rule'), ('SEMANTIC', 'Semantic'), ('IMAGE', 'Image'), ('LLM', 'LLM'), ('COMBINED', 'Combined')], default='COMBINED', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_candidates', to='taxonamy.taxonomycategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_candidates', to='products.product')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('text_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('image_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('attribute_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('CLASSIFIED', 'Classified'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='CLASSIFIED', max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_results', to='taxonamy.taxonomycategory')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_result', to='products.product')),
            ],
        ),
    ]
