# Generated by Django 6.1 on 2026-08-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
        ('products', '0001_initial'),
        ('taxonamy', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classificationcandidate',
            index=models.Index(fields=['product', 'rank'], name='class_candidate_prod_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationcandidate',
            index=models.Index(fields=['category'], name='class_candidate_category_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['confidence'], name='class_result_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['status'], name='class_result_status_idx'),
        ),
    ]
