# Generated by Django 6.1 on 2026-08-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('IMPORT', 'Import'), ('CLASSIFY', 'Classify'), ('IMAGE', 'Image'), ('ATTRIBUTE', 'Attribute'), ('FULL_PIPELINE', 'Full Pipeline')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('import_id', models.BigIntegerField(blank=True, null=True)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('last_processed_id', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'processing_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='processing__status_96bb49_idx'), models.Index(fields=['job_type'], name='processing__job_typ_d1b57f_idx'), models.Index(fields=['import_id'], name='processing__import__d005bc_idx')],
            },
        ),
    ]
