# Generated by Django 6.1 on 2026-08-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
