# Generated by Django 6.1 on 2026-08-20 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'taxonomy_attributes',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=0)),
                ('is_leaf', models.BooleanField(default=False)),
                ('taxonomy_version', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonamy.taxonomycategory')),
            ],
            options={
                'db_table': 'taxonomy_categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_categories', to='taxonamy.taxonomyattribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='taxonamy.taxonomycategory')),
            ],
            options={
                'db_table': 'category_attributes',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(max_length=500)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='taxonamy.taxonomyattribute')),
            ],
            options={
                'db_table': 'taxonomy_values',
            },
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['parent'], name='taxonomy_ca_parent__d74e32_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['shopify_id'], name='taxonomy_ca_shopify_127655_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryattribute',
            constraint=models.UniqueConstraint(fields=('category', 'attribute'), name='unique_category_attribute'),
        ),
    ]
