# Generated by Django 6.1 on 2026-08-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taxonomy_attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('full_name', models.TextField(blank=True, default='')),
                ('parent_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('is_root', models.BooleanField(default=False)),
                ('is_leaf', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taxonomy_categories',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTaxonomyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('matched_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_result', to='products.product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonamy.taxonomycategory')),
            ],
            options={
                'db_table': 'product_taxonomy_results',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='taxonamy.taxonomyattribute')),
            ],
            options={
                'db_table': 'taxonomy_values',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='taxonamy.taxonomyattribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='taxonamy.taxonomycategory')),
            ],
            options={
                'db_table': 'category_attributes',
                'unique_together': {('category', 'attribute')},
            },
        ),
    ]
