# Generated by Django 6.1 on 2026-08-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonamy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttaxonomyresult',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_taxonomy_results', to='taxonamy.taxonomycategory'),
        ),
    ]
