# Generated by Django 6.1 on 2026-08-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('taxonamy', '0002_alter_producttaxonomyresult_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttaxonomyresult',
            name='ai_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producttaxonomyresult',
            name='alternatives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='producttaxonomyresult',
            name='attributes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='producttaxonomyresult',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producttaxonomyresult',
            name='image_status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('invalid', 'Invalid')], default='not_available', max_length=30),
        ),
        migrations.AddField(
            model_name='producttaxonomyresult',
            name='review_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='producttaxonomyresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('classified', 'Classified'), ('needs_review', 'Needs Review'), ('manual_review', 'Manual Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='producttaxonomyresult',
            index=models.Index(fields=['status'], name='taxonomy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='producttaxonomyresult',
            index=models.Index(fields=['confidence'], name='taxonomy_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='producttaxonomyresult',
            index=models.Index(fields=['category'], name='taxonomy_category_idx'),
        ),
    ]
