# Generated by Django 6.1 on 2026-08-20 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_category_id', models.BigIntegerField(blank=True, null=True)),
                ('new_category_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('EDIT', 'Edit'), ('REJECT', 'Reject')], max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='products.product')),
            ],
        ),
    ]
