# Generated by Django 6.1 on 2026-08-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imports/'),
        ),
    ]
